# Generated by Django 5.2.1 on 2025-05-28 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipi',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='recipiingredientamount',
            name='Ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.ingredient'),
        ),
        migrations.AddField(
            model_name='recipiingredientamount',
            name='recipi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.recipi'),
        ),
        migrations.AddField(
            model_name='recipi',
            name='ingredients',
            field=models.ManyToManyField(through='posts.RecipiIngredientAmount', to='posts.ingredient', verbose_name='Список ингредиентов'),
        ),
    ]
