# Generated by Django 5.2.1 on 2025-05-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipiingredientamount',
            name='amount',
        ),
    ]
