# Generated by Django 5.2.1 on 2025-05-30 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_recipi_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipi',
            name='short_link',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortlink', to='posts.shorturl', verbose_name='Короткая ссылка'),
        ),
    ]
