# Generated by Django 5.2.1 on 2025-05-28 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_recipiingredientamount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipiingredientamount',
            name='amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
